# Generated by Django 4.2.19 on 2026-02-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('mrp', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('ptr', models.CharField(blank=True, max_length=10, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('quantity_inwarded', models.IntegerField(blank=True, null=True)),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inward_type', models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('return', 'Return'), ('transfer', 'Transfer')], max_length=20, null=True)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('low_stock', 'Low Stock'), ('damaged', 'Damaged'), ('reserved', 'Reserved'), ('lost', 'Lost')], default='in_stock', max_length=20)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by_user_id', models.IntegerField(blank=True, null=True)),
                ('domain_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('added', 'Added'), ('removed', 'Removed'), ('moved', 'Moved'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('reserved', 'Reserved'), ('lost', 'Lost'), ('warehouse transfer', 'Warehouse Transfer'), ('adjusted', 'Adjusted')], max_length=20, null=True)),
                ('action', models.CharField(max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by_user_id', models.IntegerField(blank=True, null=True)),
                ('domain_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackAndShelvesAndFloors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rack', models.CharField(blank=True, max_length=100, null=True)),
                ('shelf', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('rack', 'Rack'), ('shelf', 'Shelf'), ('floor', 'Floor')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by_user_id', models.IntegerField(blank=True, null=True)),
                ('domain_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_and_shelves_and_floors', to='InventoryServices.warehouse')),
            ],
        ),
    ]
