# Generated by Django 4.2.19 on 2026-02-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauthapp', '0001_initial'),
        ('InventoryServices', '0001_initial'),
        ('ProductServices', '0001_initial'),
        ('OrderServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylogs',
            name='added_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_inventory_logs', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='inventorylogs',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='inventorylogs',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='InventoryServices.inventory'),
        ),
        migrations.AddField(
            model_name='inventorylogs',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='inventorylogs',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventorylogs',
            name='rack_shelf_floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='InventoryServices.rackandshelvesandfloors'),
        ),
        migrations.AddField(
            model_name='inventorylogs',
            name='sales_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='OrderServices.salesorder'),
        ),
        migrations.AddField(
            model_name='inventorylogs',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='InventoryServices.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_inwarded_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='OrderServices.purchaseorderiteminwardedlog'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_order_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='OrderServices.purchaseorderitems'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='rack_and_shelf_and_floor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='InventoryServices.rackandshelvesandfloors'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='InventoryServices.warehouse'),
        ),
    ]
