# Generated by Django 4.2.19 on 2026-02-24 18:30

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', help_text='Type of address', max_length=20)),
                ('full_name', models.CharField(blank=True, help_text='Recipient name', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for delivery', max_length=15, null=True)),
                ('address', models.CharField(blank=True, help_text='Street address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True)),
                ('country', models.CharField(default='Bangladesh', help_text='Country', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default shipping address')),
                ('status', models.BooleanField(default=True, help_text='Active/inactive')),
                ('created_at', models.DateTimeField(blank=True, default=None, help_text='When address was created', null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, help_text='Last update time', null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='br', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brands')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='Selected size', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Selected color', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax/shipping', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost', max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, help_text='Discount from coupon', max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Final total price', max_digits=10)),
                ('paid_status', models.BooleanField(default=False, help_text='Whether payment is received')),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('visa', 'Visa Card'), ('mastercard', 'MasterCard'), ('amex', 'American Express')], default='cod', help_text='Payment method used', max_length=20)),
                ('product_status', models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', help_text='Overall order status', max_length=30)),
                ('coupon_code', models.CharField(blank=True, help_text='Coupon code if applied', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Order notes from customer')),
                ('order_date', models.DateTimeField(blank=True, db_index=True, help_text='When order was placed', null=True)),
                ('created_at', models.DateTimeField(blank=True, help_text='When order was created', null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='Last update time', null=True)),
            ],
            options={
                'verbose_name_plural': 'Cart Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(help_text='Invoice/line item number', max_length=200)),
                ('product_status', models.CharField(help_text='Status of this item', max_length=200)),
                ('item', models.CharField(help_text='Product title (snapshot)', max_length=200)),
                ('image', models.CharField(help_text='Product image URL (snapshot)', max_length=200)),
                ('size', models.CharField(blank=True, help_text='Selected size', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Selected color', max_length=50)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity ordered')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit at purchase', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total for this line item', max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, help_text='When item was added to order', null=True)),
            ],
            options={
                'verbose_name_plural': 'Cart Order Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], help_text='Current order status', max_length=20)),
                ('tracking_number', models.CharField(blank=True, db_index=True, help_text='Carrier tracking number (optional)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this status was set')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789abcd', length=10, max_length=20, prefix='prod', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('price', models.DecimalField(decimal_places=2, default='1.00', max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('specs', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('type', models.CharField(blank=True, default='100% Cotton', max_length=100, null=True)),
                ('stock_count', models.IntegerField(default=10, help_text='Total units in stock')),
                ('sizes', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra X Large'), ('XXXL', 'Extra XX Large')], default='L', max_length=10, null=True)),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='in_review', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='vend', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='product_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ProductImages',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_heading', models.TextField(blank=True, default='Thanks to Fabrything for this amazing item!', null=True)),
                ('review', models.TextField(default=None)),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ProductReviews',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of the view')),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(choices=[('popular', 'Popular Products'), ('trending', 'Trending Products'), ('personalized', 'Personalized Recommendations'), ('similar', 'Similar Products')], db_index=True, help_text='Type of recommendation being cached', max_length=20)),
                ('cache_key', models.CharField(db_index=True, help_text='Unique identifier for this cache entry', max_length=255, unique=True)),
                ('recommendations_data', models.JSONField(help_text='List of product PIDs in recommendation order')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When these recommendations were generated')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache entry expires')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Number of times this cache was accessed')),
            ],
            options={
                'verbose_name': 'Recommendation Cache',
                'verbose_name_plural': 'Recommendation Caches',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (Standard, Express, etc)', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Shipping cost in BDT', max_digits=10)),
                ('delivery_days', models.IntegerField(help_text='Estimated delivery days')),
                ('description', models.TextField(blank=True, help_text='Description of shipping method')),
                ('is_active', models.BooleanField(default=True, help_text='Is this shipping method available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text="User's minimum preferred price", max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text="User's maximum preferred price", max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabrythingapp.product')),
            ],
            options={
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
