# Generated by Django 4.2.19 on 2026-02-24 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrythingapp', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_brands',
            field=models.ManyToManyField(blank=True, help_text='Brands user prefers', related_name='preference_users', to='fabrythingapp.brand'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories user is interested in', related_name='preference_users', to='fabrythingapp.category'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(help_text='User who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationcache',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User these recommendations are for (null = global cache)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_caches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(help_text='Product that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='fabrythingapp.product'),
        ),
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(help_text='User who viewed the product', on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='fabrythingapp.product'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='fabrythingapp.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='fabrythingapp.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='fabrythingapp.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='fabrythingapp.cartorder'),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fabrythingapp.cartorder'),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fabrythingapp.cartorder'),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='fabrythingapp.product'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fabrythingapp.address'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_method',
            field=models.ForeignKey(blank=True, help_text='Shipping method selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fabrythingapp.shippingmethod'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(help_text='Customer who placed order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fabrythingapp.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrythingapp.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recommendationcache',
            index=models.Index(fields=['cache_key', 'expires_at'], name='fabrythinga_cache_k_420e03_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationcache',
            index=models.Index(fields=['user', 'cache_type'], name='fabrythinga_user_id_b264bf_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'viewed_at'], name='fabrythinga_product_dab812_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user', 'viewed_at'], name='fabrythinga_user_id_6594ad_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product'], name='fabrythinga_product_9e4c37_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='fabrythinga_rating_b5471d_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='fabrythinga_user_id_3e175e_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['-date'], name='fabrythinga_date_91df74_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'rating'], name='fabrythinga_product_e5d7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['date'], name='fabrythinga_date_a70faf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='fabrythinga_categor_290f83_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='fabrythinga_brand_i_d71805_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='fabrythinga_price_0e7296_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured'], name='fabrythinga_feature_03fa0a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='fabrythinga_status_5c3390_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-date', 'status'], name='fabrythinga_date_e61a29_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatus',
            index=models.Index(fields=['order', '-created_at'], name='fabrythinga_order_i_4d4a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatus',
            index=models.Index(fields=['status', '-created_at'], name='fabrythinga_status_e0762f_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['user', 'paid_status'], name='fabrythinga_user_id_26465b_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['-order_date'], name='fabrythinga_order_d_0e4cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['payment_method'], name='fabrythinga_payment_4c86e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size', 'color')},
        ),
    ]
