# Generated by Django 4.2.19 on 2025-03-01 16:37

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('fabrythingapp', '0002_product_vendor_alter_product_image_alter_product_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='br', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brands')),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fabrythingapp.brand'),
        ),
    ]
