# Generated by Django 4.2.19 on 2025-03-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrythingapp', '0004_product_sizes_product_stock_count_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
