# Generated by Django 4.2.19 on 2025-03-12 16:16

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fabrythingapp', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_heading',
            field=models.TextField(blank=True, default='Thanks to Fabrything for this amazing item!', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default='4', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='fabrythingapp.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(default=None),
        ),
    ]
