# Generated by Django 4.2.19 on 2025-03-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrythingapp', '0011_alter_product_rating_alter_productreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Vendor',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='fabrythingapp.brand'),
        ),
    ]
