# Generated by Django 4.2.19 on 2025-03-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrythingapp', '0013_alter_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None),
        ),
    ]
