# Generated by Django 4.2.19 on 2026-01-30 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabrythingapp', '0014_remove_product_rating_alter_productreview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text="User's minimum preferred price", max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text="User's maximum preferred price", max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_brands', models.ManyToManyField(blank=True, help_text='Brands user prefers', related_name='preference_users', to='fabrythingapp.brand')),
                ('preferred_categories', models.ManyToManyField(blank=True, help_text='Categories user is interested in', related_name='preference_users', to='fabrythingapp.category')),
                ('user', models.OneToOneField(help_text='User who owns these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(choices=[('popular', 'Popular Products'), ('trending', 'Trending Products'), ('personalized', 'Personalized Recommendations'), ('similar', 'Similar Products')], db_index=True, help_text='Type of recommendation being cached', max_length=20)),
                ('cache_key', models.CharField(db_index=True, help_text='Unique identifier for this cache entry', max_length=255, unique=True)),
                ('recommendations_data', models.JSONField(help_text='List of product PIDs in recommendation order')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When these recommendations were generated')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this cache entry expires')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Number of times this cache was accessed')),
                ('user', models.ForeignKey(blank=True, help_text='User these recommendations are for (null = global cache)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Cache',
                'verbose_name_plural': 'Recommendation Caches',
                'indexes': [models.Index(fields=['cache_key', 'expires_at'], name='fabrythinga_cache_k_420e03_idx'), models.Index(fields=['user', 'cache_type'], name='fabrythinga_user_id_b264bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp of the view')),
                ('product', models.ForeignKey(help_text='Product that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='fabrythingapp.product')),
                ('user', models.ForeignKey(help_text='User who viewed the product', on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['product', 'viewed_at'], name='fabrythinga_product_dab812_idx'), models.Index(fields=['user', 'viewed_at'], name='fabrythinga_user_id_6594ad_idx')],
            },
        ),
    ]
