# Generated by Django 4.2.19 on 2026-01-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrythingapp', '0015_userpreferences_recommendationcache_productview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date'], 'verbose_name_plural': 'ProductReviews'},
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['user', 'paid_status'], name='fabrythinga_user_id_26465b_idx'),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['-order_date'], name='fabrythinga_order_d_0e4cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['date'], name='fabrythinga_date_a70faf_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='fabrythinga_categor_290f83_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='fabrythinga_brand_i_d71805_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='fabrythinga_price_0e7296_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured'], name='fabrythinga_feature_03fa0a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='fabrythinga_status_5c3390_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-date', 'status'], name='fabrythinga_date_e61a29_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product'], name='fabrythinga_product_9e4c37_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='fabrythinga_rating_b5471d_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='fabrythinga_user_id_3e175e_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['-date'], name='fabrythinga_date_91df74_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'rating'], name='fabrythinga_product_e5d7fd_idx'),
        ),
    ]
