# Generated by Django 4.2.19 on 2026-01-30 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabrythingapp', '0016_alter_product_options_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App')], help_text='Type of notification', max_length=20)),
                ('subject', models.CharField(help_text='Notification subject/title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When notification was sent')),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read notification')),
            ],
            options={
                'verbose_name': 'Order Notification',
                'verbose_name_plural': 'Order Notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], help_text='Current order status', max_length=20)),
                ('tracking_number', models.CharField(blank=True, db_index=True, help_text='Carrier tracking number (optional)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this status was set')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Standard, Express, Overnight', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='User-facing description', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Shipping cost', max_digits=10)),
                ('delivery_days', models.IntegerField(help_text='Expected delivery days (e.g., 3 for 3-5 days)')),
                ('max_delivery_days', models.IntegerField(default=1, help_text='Maximum delivery days')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this shipping option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'ordering': ['delivery_days', 'cost'],
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='cartorder',
            options={'ordering': ['-order_date'], 'verbose_name_plural': 'Cart Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Cart Order Items'},
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', help_text='Type of address', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Bangladesh', help_text='Country', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When address was created', null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, help_text='Recipient name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as default shipping address'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for delivery', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Last update time', null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon code if applied', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='When order was created', null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount from coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Order notes from customer'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('visa', 'Visa Card'), ('mastercard', 'MasterCard'), ('amex', 'American Express')], default='cod', help_text='Payment method used', max_length=20),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='Shipping address', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fabrythingapp.address'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before tax/shipping', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, help_text='Last update time', null=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='color',
            field=models.CharField(blank=True, help_text='Selected color', max_length=50),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='When item was added to order', null=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='fabrythingapp.product'),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='size',
            field=models.CharField(blank=True, help_text='Selected size', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, help_text='Street address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=True, help_text='Active/inactive'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When order was placed', null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(default=False, help_text='Whether payment is received'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final total price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', help_text='Overall order status', max_length=30),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=models.ForeignKey(help_text='Customer who placed order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.CharField(help_text='Product image URL (snapshot)', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='invoice',
            field=models.CharField(help_text='Invoice/line item number', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='item',
            field=models.CharField(help_text='Product title (snapshot)', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fabrythingapp.cartorder'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per unit at purchase', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(help_text='Status of this item', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity ordered'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total for this line item', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='cartorder',
            index=models.Index(fields=['payment_method'], name='fabrythinga_payment_4c86e4_idx'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='order',
            field=models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='fabrythingapp.cartorder'),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='order',
            field=models.ForeignKey(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fabrythingapp.cartorder'),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='user',
            field=models.ForeignKey(help_text='Recipient user', on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_method',
            field=models.ForeignKey(blank=True, help_text='Shipping method selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fabrythingapp.shippingmethod'),
        ),
        migrations.AddIndex(
            model_name='orderstatus',
            index=models.Index(fields=['order', '-created_at'], name='fabrythinga_order_i_4d4a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatus',
            index=models.Index(fields=['status', '-created_at'], name='fabrythinga_status_e0762f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordernotification',
            index=models.Index(fields=['user', '-sent_at'], name='fabrythinga_user_id_6814f4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordernotification',
            index=models.Index(fields=['order', '-sent_at'], name='fabrythinga_order_i_92f3fd_idx'),
        ),
    ]
