# Generated by Django 4.2.19 on 2026-02-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauthapp', '0001_initial'),
        ('ProductServices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='added_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_products', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ProductServices.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='added_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_product_reviews', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='reviewed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_product_reviews', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productquestions',
            name='added_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_product_questions', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productquestions',
            name='answered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_product_questions', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productquestions',
            name='asked_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asked_product_questions', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productquestions',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='productquestions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ProductServices.products'),
        ),
        migrations.AddField(
            model_name='productquestions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_questions', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='categories',
            name='added_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_categories', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='categories',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='categories',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ProductServices.categories'),
        ),
    ]
