# Generated by Django 4.2.19 on 2026-02-07 20:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.TextField(blank=True, max_length=100, null=True)),
                ('is_menu', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('module_url', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('bio', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('account_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, null=True)),
                ('role', models.CharField(blank=True, choices=[('customer', 'Customer'), ('admin', 'Admin'), ('vendor', 'Vendor'), ('delivery', 'Delivery'), ('support', 'Support'), ('manager', 'Manager'), ('staff', 'Staff'), ('superadmin', 'Super Admin'), ('manager', 'Manager'), ('supplier', 'Supplier')], max_length=20, null=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('sales', 'Sales'), ('marketing', 'Marketing'), ('engineering', 'Engineering'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('customer_support', 'Customer Support'), ('it', 'IT'), ('legal', 'Legal'), ('product_management', 'Product Management')], max_length=50, null=True)),
                ('designation', models.CharField(blank=True, choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('analyst', 'Analyst'), ('consultant', 'Consultant'), ('intern', 'Intern'), ('ceo', 'CEO'), ('cto', 'CTO'), ('cfo', 'CFO'), ('coo', 'COO'), ('cmo', 'CMO'), ('hr_manager', 'HR Manager'), ('sales_representative', 'Sales Representative'), ('customer_support_agent', 'Customer Support Agent'), ('data_scientist', 'Data Scientist'), ('product_manager', 'Product Manager')], max_length=50, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_device', models.CharField(blank=True, max_length=100, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TaKa', 'TK')], max_length=10, null=True)),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_type', models.CharField(blank=True, choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_users', to='userauthapp.user')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('domain_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='userauthapp.modules')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='userauthapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserhippingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='userauthapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='modules',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_modules', to='userauthapp.user'),
        ),
        migrations.AddField(
            model_name='modules',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='userauthapp.modules'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='userauthapp.user')),
            ],
        ),
    ]
