# Generated by Django 4.2.19 on 2025-03-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
