# Generated by Django 4.2.19 on 2025-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthapp', '0003_user_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
