# Generated by Django 4.2.19 on 2026-02-24 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabrythingapp', '0001_initial'),
        ('OrderServices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryServices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='outwarded_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sooutward_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='received_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sooutward_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='sales_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_outward_logs', to='OrderServices.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderoutwardedlog',
            name='sales_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sooutward_logs', to='OrderServices.salesorderitems'),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderlogs',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_logs', to='OrderServices.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soi_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='cancelled_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soi_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soi_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrythingapp.product'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soi_returned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='OrderServices.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='shipped_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soi_shipped_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitems',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soi_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemoutwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemoutwardedlog',
            name='received_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soioutward_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemoutwardedlog',
            name='sales_order_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soioutward_logs', to='OrderServices.salesorderitems'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cancelled_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='recieved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='so_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderlogs',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_logs', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='approved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='cancelled_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabrythingapp.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='recieved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='returned_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_returned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitems',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderiteminwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderiteminwardedlog',
            name='purchase_order_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poiinward_logs', to='OrderServices.purchaseorderitems'),
        ),
        migrations.AddField(
            model_name='purchaseorderiteminwardedlog',
            name='received_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poiinward_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_inward_logs', to='OrderServices.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='purchase_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poinward_logs', to='OrderServices.purchaseorderitems'),
        ),
        migrations.AddField(
            model_name='purchaseorderinwardedlog',
            name='received_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poinward_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cancelled_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_cancelled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='recieved_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryServices.warehouse'),
        ),
    ]
